name: Build docker

on:
  push:

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        run: docker build . -f infrastructure/Dockerfile
